version: "3"

vars:
    GO_MODULE_PATH: "github.com/vwency/intern-task/"

tasks:
    run-subpub:
        desc: Run subpub
        cmds:
          - go run ./cmd/subpub

    test-subpub:
        desc: Run tests for client and server
        cmds:
        - go test ./tests/subpub/
  
    test-subpub-server:
      desc: Run tests for client and server
      cmds:
      - go run ./tests/subpub/client

    proto-generate:
        desc: Generate gRPC code from proto
        cmds:
          - protoc --proto_path=./proto --go_out=./proto --go-grpc_out=./proto --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative ./proto/**/*.proto

    generate-gomod:
        desc: Generate go.mod preserving requirements
        cmds:
          - chmod +x ./generate_gomod.sh
          - ./generate_gomod.sh
          - go mod edit -fmt

    update-deps:
        desc: Update dependencies list
        cmds:
          - go mod tidy
          - chmod +x ./update_deps.sh
          - ./update_deps.sh
          - go mod edit -fmt
          - go mod vendor

    clean-unused-deps:
        desc: Remove unnecessary dependencies from go.mod and go.sum
        cmds:
          - go mod tidy
          - go mod vendor
          - go mod verify
          - echo "Unused dependencies removed successfully"
